# Generated by Django 5.1.1 on 2024-10-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='hero_headshots/'),
        ),
    ]
